[[plugins]]
repo = 'Shougo/dein.vim'

# ------------------------------------
# colorscheme tender setting
# ------------------------------------
#[[plugins]]
#repo = 'jacoborus/tender.vim'
#hook_add = '''
#    colorscheme tender
#    set background=dark
#    syntax on
#    set t_Co=256
#    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
#'''

#vimfilerを使うために必要
#[[plugins]]
#repo =  'Shougo/unite.vim'

#ディレクトリ表示
#[[plugins]]
#repo = 'Shougo/vimfiler'

#[[plugins]]
#repo = "morhetz/gruvbox"

#vim ステータスバーを装飾する
[[plugins]]
repo = "vim-airline/vim-airline"

#https://qiita.com/kooooooooooooooooohe/items/fb106e0a0f0969b4ee38
[[plugins]]
repo = 'Yggdroot/indentLine'

#検索件数表示
[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'vim-scripts/grep.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = """
source ~/.config/nvim/plugins/denite.rc.vim
"""

#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
